version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: rohit
    #   MONGO_INITDB_ROOT_PASSWORD: rohit
    ports:
      - 27017:27017
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_ADMINUSERNAME: rohit
      # ME_CONFIG_MONGODB_ADMINPASSWORD: rohit
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
